### ISSUE TITLE
最近增加的几个配置是什么用处啊, 希望能增加文档

### ISSUE THREAD

**Issue by guileen** [jiangmiao/simple-javascript-indenter#11]

**Comment by jiangmiao** [comment]
哪个配置？没有修改过插件满久了。只有一个g:SimpleJsIndenter_GreedyIndent最后添加，但用处不大，对问题 #11 理解错误误添加，未来可能会移除。
当 g:SimpleJsIndenter_GreedyIndent = 0
把

```
foo({
}, b());
```

会缩进为

```
foo({
  }, b());
```

主要符号前置的风格对我来说有点怪异，而且符号后置的缩进基本上没有bug，对符号前置的处理方式略显hack，就搁置了。
