### ISSUE TITLE
switch-case blocks not indenting properly

### ISSUE THREAD

**Issue by broofa** [jiangmiao/simple-javascript-indenter#2]
Hi jiangmiao, thanks for this script!  I can't tell you how long I've been searching for a decent JS indent solution, and this is definitely the best I've found so far.  Nearly perfect! ... except for one bug: switch-case blocks aren't indenting properly.

E.g.  I would expect a switch block to indent like this:

```
switch (foo) {
  case 1:
    // blah
    break;
  case 2:
    // blah
    break;
  default:
    // blah
    return;
}
```

.... but what I'm getting is this:

```
switch (foo) { 
case 1: 
  // blah 
  break; 
case 2: 
  // blah 
  break; 
default: 
  // blah 
  return; 
} 
```

**Comment by jiangmiao** [comment]
Hello broofa,
Thank you for reporting,
For perfect indenting in switch, I haven't got good idea, so current script didn't support 'switch'. now I have just added solution 2 (see below) in 1.4.0, it's not perfect solution but better than nothing.

Solution 1: 
Indenting effect: It's the same as you expect

<pre>
switch (foo) {
  // indented by prev line
  case 1: // Current line indent 0, Next line indent 1
    // blah
    break;

   case 2: // Current line indent -1, Next line indent 1
     break;

   case 3: { // Current line indent -1, Next line indent 1
     break;
   }

   case 4:  // Current line indent 0, Next line indent 1
     break;

   case 5: break; // Current line indent -1, Next line indent 0
   default: // Current line indent -1, Next line indent 1
     // blah
     return;
} // Current line indent -2, Next line indent 0,  
</pre>

all above indenting condition could be solved except close switch, it have to check matched bracket { is opened by switch or not, it will decrease the performance a lot.
so user have to add switch indetifier. such as ' } // end of switch ' to indent -2 instead indent -1.

Solution 2:  Current using.
Indent effect:

<pre>
switch (foo) {
 case 1:  // Current line indent -1/2, Next line indent +1/2
  break;

 case 2: 
  break;

 case 3: { 
    break; 
  } // indent 1/2 according to 'case 3:'

 case 4:  
  break;

 case 5: break; 
 default: 
  return;
} 
</pre>


If shiftwidth is 2, then indent 1 seems too short.

**Comment by broofa** [comment]
Thanks for the quick work!  Unfortunately this doesn't do what I had hoped. (sorry!)

The only issue I had is that the contents of the switch block need to be indented one level.  I.e. I think it's a bug that the switch statements {}-brackets don't add +sw to 'ind' for everything inside the switch statement.  In fact, in looking at the code, I'm not sure why that wasn't happening before. Do you know?

I'm confused by your last commit - I would never expect to indent by just sw/2.  That should always be sw.  Also, I've never seen real code put {}-brackets around a case block, like "case 3".  I wouldn't want to have to start doing that just to get indentation to work.

Thanks again for working on this though.  As I said, I really do appreciate it!

**Comment by jiangmiao** [comment]
for switch code in old 1.3.4, It shows

<pre>
switch (foo) { 
  case 1: 
  // blah 
  break; 

  case 2: 
  // blah 
  break; 

  default: 
  // blah 
  return; 
} 
</pre>

Here., the 'case' is indented too.  The script did nothing with 'switch' and ':' at all,  It process 'switch () {' as a normal function and ':' as normal text. 

Sorry, I have technology issue as I talked in solution 1. 

the big problem is the way to close switch, '}' will indent -2 instead -1, all others '}' indent -1,  so script have to check '}'  is a part of 'switch' or not.  if check it automatically the a closure is very large, such as 1000 lines,  each checking will take a very long time. 

so my idea is mark '}'  as '} // end of switch' marked as switch by manual. but I think it's not a good idea, so I hang it on and goto solution 2. 

about  case 3, it could be
case 3:  if ( foo ) {
  do something;
} 
or so, but it's not a problem, it could be solved.

What's the indented 'switch' code looks like currently in your vim?

**Comment by broofa** [comment]
Hi, sorry to take so long to get back to you on this.  Here's what switch indents look like currently for me (v1.4.1):

```
switch (foo) { 
 case 1: 
  blah 
  break; 

 case 2: 
  // blah 
  break; 

 default: 
  // blah 
  return; 
} 
```

As I mentioned before, I would never expect any indent script to indent by less than 'sw'.  So the sw/2 indentation here seems odd, and causes at least one problem: The ">>" command doesn't retain the indentation.  E.g. When I select the switch block and do ">>", I get this:

```
  switch (foo) { 
  case 1: 
    blah 
    break; 

  case 2: 
    // blah 
    break; 

  default: 
    // blah 
    return; 
  } 
```

One last comment, regarding the "checking a 1000 line '{}' closure will be slow" issue.  I don't think that's worth worrying about - the case is rare enough I don't think it justifies not supporting proper indentation.  (Personally I _never_ write switch statements that are that large.  Anything that big gets refactored into separate functions, so my switch statements are almost never > 40-50 lines).   Maybe make this a configuration option, where proper switch indenting is on by default.  If people have performance issues, they can disable it?

**Comment by guileen** [comment]
I have the same problem, my default indent is 2. and swith case both indent 1.

**Comment by jiangmiao** [comment]
{...} sometimes large (more than 200 lines), jquery.js even have thousands lines in one {...}. so does when wrap the whole js in one function or a big hash. 
in 1.3.4 switch...case is not indented (equal g:SimpleJsIndenter_CaseIndentLevel = 0), 
in 1.4.0 'case' indent negative half of shiftwidth (equal g:SimpleJsIndenter_CaseIndentLevel = -0.5). 
Now I've added a new option g:SimpleJsIndenter_CaseIndentLevel (default is 0) to control indent level of case in trunk.  also could try set it to -1 to indent -1 shiftwidth.
