### ISSUE TITLE
Make "brief mode" the default?

### ISSUE THREAD

**Issue by broofa** [jiangmiao/simple-javascript-indenter#3]
Does anyone _not_ have "brief mode" turned on?  Kind of feels like this should be the default behavior.  But that's just my opinion.

**Comment by jiangmiao** [comment]
Thank you for suggestion, I consider it before, but what I worried is some code doesn't close the bracket in right way, then cause indenting incorrected in brief mode.
so turn it on by manul could let user keep 'I'm using brief mode' in mind.
