### ISSUE TITLE
need indenter update before <Enter> pressed.

### ISSUE THREAD

**Issue by guileen** [jiangmiao/simple-javascript-indenter#4]
The indenter of `})` was update when `<Enter>` pressed.  but sometimes I do not want to press `<Enter>`, because I am edit the file from middle, I will press `<Esc>`, but I cant get the correct indenter, So I have to press `<Enter><Esc>dd`, can I just press `<Esc>` or when I press `)` I got the correct indenter at once?

**Comment by jiangmiao** [comment]
Thanks, the issue has solved. 

<pre>
@@ -23,7 +23,7 @@ let b:indented = 0
 let b:in_comment = 0
 
 setlocal indentexpr=GetJsIndent()
-setlocal indentkeys+=0},0),0],0=*/,0=/*,*<Return>
+setlocal indentkeys+==},=),=],0=*/,0=/*,*<Return>
 if exists("*GetJsIndent")
   finish 
 endif
</pre>


another tips: you could press <Esc>== to indent current line.

**Comment by guileen** [comment]
thanks, awesome.
