### ISSUE TITLE
Multi-line /*-style comment indentation

### ISSUE THREAD

**Issue by broofa** [jiangmiao/simple-javascript-indenter#5]
Standard practice for /*-style is to align the first '*', like so:

```
/**
 * This is a comment
 */
```

However this script aligns the first character non-whitespace character:

```
/**
* This is a comment
*/
```

Any chance you can support the the '*'-aligned style?

**Comment by guileen** [comment]
no vote feature on github?
+1

**Comment by jiangmiao** [comment]
The style has changed to 

<pre>
/**
 * This is a comment
 */
</pre>

In 1.4.1

**Comment by broofa** [comment]
Awesome, thanks!

**Comment by broofa** [comment]
BTW, on an unrelated note, you should add this to the indent.js file header:

```
" github: https://github.com/jiangmiao/simple-javascript-indenter
```

As this file gets copied around, as I'm sure it will, this will make it easier for people to discover where it came from.

**Comment by jiangmiao** [comment]
Thanks, I've added them.

<pre>
Homepage: http://www.vim.org/scripts/script.php?script_id=3227
Repository: https://github.com/jiangmiao/simple-javascript-indenter
</pre>
